// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx62iaRgWpzzy2t1iPkJ5wT81OpoGnDNw',
    appId: '1:680685794316:web:54feb9f8c6c1587118ea29',
    messagingSenderId: '680685794316',
    projectId: 'incoming-product-checker',
    authDomain: 'incoming-product-checker.firebaseapp.com',
    storageBucket: 'incoming-product-checker.appspot.com',
    measurementId: 'G-8RL7V45HR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCTeyZ1RvRrQtJHzLxU5uGZlY7ZLYYCc',
    appId: '1:680685794316:android:ca1cece94e28119a18ea29',
    messagingSenderId: '680685794316',
    projectId: 'incoming-product-checker',
    storageBucket: 'incoming-product-checker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MPyoKlpSnjttQjeCQ0ynrZYeFdzs1mI',
    appId: '1:680685794316:ios:517068ab9c75bbac18ea29',
    messagingSenderId: '680685794316',
    projectId: 'incoming-product-checker',
    storageBucket: 'incoming-product-checker.appspot.com',
    iosBundleId: 'com.example.barcodeChecking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MPyoKlpSnjttQjeCQ0ynrZYeFdzs1mI',
    appId: '1:680685794316:ios:517068ab9c75bbac18ea29',
    messagingSenderId: '680685794316',
    projectId: 'incoming-product-checker',
    storageBucket: 'incoming-product-checker.appspot.com',
    iosBundleId: 'com.example.barcodeChecking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx62iaRgWpzzy2t1iPkJ5wT81OpoGnDNw',
    appId: '1:680685794316:web:4de3f63ef494fb0218ea29',
    messagingSenderId: '680685794316',
    projectId: 'incoming-product-checker',
    authDomain: 'incoming-product-checker.firebaseapp.com',
    storageBucket: 'incoming-product-checker.appspot.com',
    measurementId: 'G-XKN91DHCMJ',
  );
}
